### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by sharmasaurabh1** [srmklive/laravel-paypal#103]
Hi Team,

I appreciate for your great work on paypal plugin.

But I need to know about few things, Please check

![untitled](https://cloud.githubusercontent.com/assets/18680313/26000363/3fdeb052-3746-11e7-8b40-bf030dccda1b.png)

I have implement all the thing according to shared in your doc for adaptive payment, but I am getting above error. I am using laravel 5.1. Please check and let me know.

Also I have set return and cancel URL, But I am not getting any response from paypal, so can you guide me how I can get the payment response from the paypal

**Comment by srmklive** [comment]
Can you tell me which version of the package are you using?

**Comment by sharmasaurabh1** [comment]
I am using  "srmklive/paypal": "~1.0"

**Comment by sharmasaurabh1** [comment]
still getting same error

**Comment by srmklive** [comment]
Ok. Looking into this issue. Meanwhile i would suggest that you create your own class which extends the AdaptivePayments class and add your changes there.

**Comment by sharmasaurabh1** [comment]
Thanks, I will wait for your response,

I think error is generating from 

filter(function ($value, $key) {
            return (($key === 'feesPayer') && empty($value)) ?: $value;
        });

so I think you have to workout on that part, its a line number 89 of AdaptivePayments.php

**Comment by srmklive** [comment]
Issue is fixed.

**Comment by sharmasaurabh1** [comment]
So how you the fix that issue , still it is running

**Comment by sharmasaurabh1** [comment]
Still Issue is not fixed, please check it again for adaptive payment

**Comment by srmklive** [comment]
Buddy its fixed. You need to check your code.

**Comment by sharmasaurabh1** [comment]
According to you fixed a code, can I update my composer on version 1.1 ?

**Comment by sharmasaurabh1** [comment]
As you write down in the document, I am using code like:-



$provider = new AdaptivePayments;
$data = [
            'receivers' => [
                [
                    'email' => 'xyz@gmail.com',
                    'amount' => 10,
                    'primary' => true,
                ],
                [
                    'email' => 'abc@gmail.com',
                    'amount' => 5,
                    'primary' => false
                ]
            ],
            'payer' => 'EACHRECEIVER', // (Optional) Describes who pays PayPal fees. Allowed values are: 'SENDER', 'PRIMARYRECEIVER', 'EACHRECEIVER' (Default), 'SECONDARYONLY'
            'return_url' => url('http://xyz.com/donation/test1payment'),
            'cancel_url' => url('http://xyz.com/donation/test1payment'),
        ];
        
        $response = $provider->createPayRequest($data);
        $redirect_url = $provider->getRedirectUrl('approved', $response['payKey']);
        return redirect($redirect_url);


and configure as mentioned in the doc but still getting error in adaptivePayments.php on line number 89.

**Comment by sharmasaurabh1** [comment]
Hi Team,

I think you should have to use

private function setPayRequestDetails($data)
    {
       $this->post = $this->setRequestData([
            'actionType'        => 'PAY',
            'currencyCode'      => $this->currency,
            'receiverList'      => [
                'receiver'      => $data['receivers'],
            ],
            'returnUrl'         => $data['return_url'],
            'cancelUrl'         => $data['cancel_url'],
            'requestEnvelope'   => $this->setEnvelope(),
            'feesPayer'         => (empty($data['payer'])?null:$data['payer']),
        ]);
       
    } 

in the adaptivePayments.php.. It will works.

my next query is you are using parallel adaptive payment or chained adaptive payment in this API

Please revert me back soon.

**Comment by srmklive** [comment]
I have tagged a new release. You can change the composer version to `~1.0`. This package doesn't fully support Adaptive Payments. I have not worked on this enough only partially. However, if you are willing we can work on the Adaptive Payments support in this package.
