### ISSUE TITLE
papyal_link is null

### ISSUE THREAD

**Issue by snax4a** [srmklive/laravel-paypal#229]
Hello when doing expressCheckout my paypal_link is null
i FIlled in  api username, api password and api secret in .env file but dont know what to fill in api certificate so i left this blank

So im getting: 
`Object of class Illuminate\Routing\Redirector could not be converted to string`
Im using sandbox

**Comment by snax4a** [comment]
i noticed that if i set validate_ssl in paypal.php it works i mean it redirects me to paypal

**Comment by srmklive** [comment]
Refer to closed issues section. It has been addressed in #101, #102 etc

**Comment by snax4a** [comment]
I saw that but it still cant help me i set up api credentials from my business paypal sandbox account i cloned your demo project and i get this error.
You guys only redirect to other issues but there is no answer, i read all of them.
Thats how looks my .env file
`PAYPAL_SANDBOX_API_USERNAME=csgolombard-facilitator-1_api1.gmail.com
PAYPAL_SANDBOX_API_PASSWORD=D6DRXKVF7QQRFL4D
PAYPAL_SANDBOX_API_SECRET=At-lD.ebJxipTWa3Fr92PQtDSOt8ApuMSnj.-edcwDL79wqIDj3q1PGp`

i also tried with your demo api credentials, the same error, maybe its some problem with my OS i use windows

**Comment by snax4a** [comment]
maybe there is problem with paypal account i just created sandbox account in sandbox > accounts section but you say i need some express checkout account

**Comment by friana** [comment]
Hi everyone,

I currently develop web-app that requires online payment.  As I research about Paypal integration in Laravel I saw this laravel plugin for processing payments through PayPal. But after I clone it I had encounter the same issue. 

I tried dd($response) , I get this response

> array:3 [▼
>   "type" => "error"
>   "message" => ""
>   "paypal_link" => null
> ]

To solve the issue I changed some configuration at paypal.php
I add **validate_ssl => false,**

![Paypal issues](https://user-images.githubusercontent.com/48547463/54341776-a7b0a380-4675-11e9-9dac-0ea2ae4d2e2b.png)

Note: Make sure that the following are consider before you apply the validate_ssl

- Correct **API credentials.**

- Change **Invoice_prefix** (For unique Invoice, you can change it to paypal.php)
_Also note about **PAYPAL_SANDBOX_API_SECRET_**
Instead of putting API Secret , Put the **Signature**  

![Paypal issues1](https://user-images.githubusercontent.com/48547463/54342670-0a0aa380-4678-11e9-8324-f48753bb0c8f.png)


I hope it will help you. Thanks

**Comment by tomas8801** [comment]
after hours of finding the solution I got it, thanks!!

**Comment by Punjtani** [comment]
Thanks @friana  after hours of finding the solution I got it, thanks!!

**Comment by hrr2000** [comment]
Thanks @friana

**Comment by 82solutions** [comment]
array:3 [▼
  "type" => "error"
  "message" => ""
  "paypal_link" => null
]
this issue not resolve in my code
